version: '2.1'

services:
  bulk-scan-service:
    extends:
      file: docker-compose-core.yml
      service: service
    environment:
      - FLYWAY_ENABLED=true
    depends_on:
      - bulk-scan-flyway
  bulk-scan-database:
    extends:
      file: docker-compose-core.yml
      service: database
    volumes:
      - bulk-scan-database-data:/var/lib/postgresql/data
  bulk-scan-flyway:
    build:
      context: docker/flyway
    image: hmcts/bulk-scan-flyway
    container_name: bulk-scan-flyway
    environment:
      - BULK_SCANNING_DB_PASSWORD
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    depends_on:
      bulk-scan-database:
        condition: service_healthy
    command: bulk-scan-database 5432 bulkscanner $BULK_SCANNING_DB_PASSWORD bulk_scan public

volumes:
  bulk-scan-database-data:
