version: '2.1'

services:
  service:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: hmcts/bulk-scan-service
    container_name: bulk-scan-service
    environment:
      - APPINSIGHTS_INSTRUMENTATIONKEY
      - FLYWAY_ENABLED=${FLYWAY_ENABLED:-false}
      - FLYWAY_NOOP_STRATEGY
      - BULK_SCANNING_DB_HOST=bulk-scan-database
      - BULK_SCANNING_DB_PORT
      - BULK_SCANNING_DB_NAME
      - BULK_SCANNING_DB_CONN_OPTIONS
      - BULK_SCANNING_DB_USER_NAME
      - BULK_SCANNING_DB_PASSWORD
      # these environment variables are used by java-logging library
      - ROOT_APPENDER
      - JSON_CONSOLE_PRETTY_PRINT
      - ROOT_LOGGING_LEVEL
      - REFORM_SERVICE_TYPE
      - REFORM_SERVICE_NAME
      - REFORM_TEAM
      - REFORM_ENVIRONMENT
      - LOGBACK_DATE_FORMAT
      - LOGBACK_REQUIRE_THREAD
      - LOGBACK_REQUIRE_ALERT_LEVEL=false
      - LOGBACK_REQUIRE_ERROR_CODE=false
    ports:
      - $SERVER_PORT:$SERVER_PORT
  database:
    build:
      context: docker/database
    image: hmcts/bulk-scan-database
    container_name: bulk-scan-database
    environment:
      - BULK_SCANNING_DB_PASSWORD
    ports:
      - 5429:5432
