test-url: ${TEST_URL:http://localhost:8581}
test-s2s-name: ${TEST_S2S_NAME}
test-s2s-url: ${TEST_S2S_URL}
test-s2s-secret: ${TEST_S2S_SECRET}

offline-mode: ${LAUNCH_DARKLY_OFFLINE_MODE:false}
sdk-key: ${LAUNCH_DARKLY_SDK_KEY:AAAAAAAAAAAAAAAA}

# no communication with Service Bus
spring.profiles.active=service-bus-stub
