server:
  port: 8581

management:
  endpoints:
    web:
      base-path: /

spring:
  application:
    name: Bulk Scanning
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${BULK_SCANNING_DB_HOST:localhost}:${BULK_SCANNING_DB_PORT:5432}/${BULK_SCANNING_DB_NAME:bulkscans}${BULK_SCANNING_DB_CONN_OPTIONS:}
    username: ${BULK_SCANNING_DB_USER_NAME:bulkscanner}
    password: ${BULK_SCANNING_DB_PASSWORD:}
    properties:
      charSet: UTF-8
    hikari:
      minimumIdle: 2
      maximumPoolSize: 10
      idleTimeout: 10000
      poolName: BulkScanHikariCP
      maxLifetime: 7200000
      connectionTimeout: 30000
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            # silence the 'wall-of-text' - unnecessary exception throw about blob types
            non_contextual_creation: true

info:
  app:
    name: Bulk Scanning
    description: Ingest scanned documents.

storage:
  account_name: ${STORAGE_ACCOUNT_NAME:bulkscanning}
  key: ${STORAGE_KEY:dGVzdA==} #Base 64 encoded

accesstoken:
  serviceConfig:
    - serviceName: sscs
      validity: ${SAS_TOKEN_VALIDITY:300} #In seconds

scan:
  delay: ${SCAN_DELAY:30000} # In milliseconds
