server:
  port: 8581

management:
  endpoints:
    web:
      base-path: /

spring:
  application:
    name: Bulk Scanning

info:
  app:
    name: Bulk Scanning
    description: Ingest scanned documents.

storage:
  account_name: ${STORAGE_ACCOUNT_NAME:bulkscanning}
  key: ${STORAGE_KEY:dGVzdA==} #Base 64 encoded

accesstoken:
  serviceConfig:
    - serviceName: sscs
      permissions: WRITE,LIST
      validity: ${SSCS_SAS_TOKEN_VALIDITY:300} #In seconds
