server:
  port: 8581

management:
  endpoints:
    web:
      base-path: /

spring:
  application:
    name: Bulk Scanning

info:
  app:
    name: Bulk Scanning
    description: Ingest scanned documents.

storage:
  account_name: ${STORAGE_ACCOUNT_NAME}
  key: ${STORAGE_KEY}
