server:
  port: 8581

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /
  health:
    mail:
      enabled: false

# liveness alert settings depend on application name, if it is changed alert configuration must also be adjusted
# https://github.com/hmcts/bulk-scan-shared-infrastructure/blob/master/liveness-alert.tf
spring:
  application:
    name: Bulk Scan Processor
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${BULK_SCANNING_DB_HOST:localhost}:${BULK_SCANNING_DB_PORT:5435}/${BULK_SCANNING_DB_NAME:bulkscans}${BULK_SCANNING_DB_CONN_OPTIONS:}
    username: ${BULK_SCANNING_DB_USER_NAME:bulkscans}
    password: ${BULK_SCANNING_DB_PASSWORD:}
    properties:
      charSet: UTF-8
    hikari:
      minimumIdle: 2
      maximumPoolSize: 10
      idleTimeout: 10000
      poolName: BulkScanHikariCP
      maxLifetime: 7200000
      connectionTimeout: 30000
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        jdbc:
          lob:
            # silence the 'wall-of-text' - unnecessary exception throw about blob types
            non_contextual_creation: true
  mail:
    host: ${SMTP_HOST}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    test-connection: true

# setting env vars + defaults as env vars will be overridden otherwise
monitoring:
  incomplete-envelopes:
    cron: ${INCOMPLETE_ENVELOPES_TASK_CRON:0 0 9 ? * MON-FRI} # can be discussed later
    enabled: ${INCOMPLETE_ENVELOPES_TASK_ENABLED:true}
  no-new-envelopes:
    enabled: ${NO_NEW_ENVELOPES_TASK_ENABLED}

reports:
  cron: ${REPORTS_CRON:0 0 18 ? * MON-FRI}
  recipients: ${REPORTS_RECIPIENTS:}

info:
  app:
    name: Bulk Scanning
    description: Ingest scanned documents.

storage:
  account_name: ${STORAGE_ACCOUNT_NAME:bulkscansandbox}
  key: ${STORAGE_KEY:dGVzdA==} #Base 64 encoded
  blob_lease_timeout: ${STORAGE_BLOB_LEASE_TIMEOUT:15}
  blob_processing_delay_in_minutes: ${STORAGE_BLOB_PROCESSING_DELAY_IN_MINUTES:0}
  signature_algorithm: ${STORAGE_BLOB_SIGNATURE_ALGORITHM:sha256withrsa}  # none or sha256withrsa
  public_key_der_file: ${STORAGE_BLOB_PUBLIC_KEY:test_public_key.der} # public key file in der format
  blob_copy_timeout_in_millis: ${BLOB_COPY_TIMEOUT_IN_MILLIS:30000}
  blob_copy_polling_delay_in_millis: ${BLOB_COPY_POLLING_DELAY_IN_MILLIS:500}
  proxy_enabled: ${STORAGE_PROXY_ENABLED:false}
  proxy_host: proxyout.reform.hmcts.net
  proxy_port: 8080
  blob_selected_container: ${STORAGE_BLOB_SELECTED_CONTAINER}

queues:
  envelopes:
    connection-string: ${QUEUE_ENVELOPE_SEND}
    queue-name: envelopes
  processed-envelopes:
    connection-string: ${QUEUE_PROCESSED_ENVELOPES_READ}
    queue-name: processed-envelopes
  notifications:
    connection-string: ${QUEUE_NOTIFICATIONS_SEND}
    queue-name: notifications
  read-notifications:
    connection-string: ${QUEUE_NOTIFICATIONS_READ}
    queue-name: notifications
    enabled: ${ERROR_NOTIFICATIONS_ENABLED:false}

accesstoken:
  serviceConfig:
    - serviceName: sscs
      validity: ${SAS_TOKEN_VALIDITY:300} #In seconds
    - serviceName: bulkscan
      validity: ${SAS_TOKEN_VALIDITY:300} #In seconds
    - serviceName: probate
      validity: ${SAS_TOKEN_VALIDITY:300} #In seconds
    - serviceName: divorce
      validity: ${SAS_TOKEN_VALIDITY:300} #In seconds
    - serviceName: finrem
      validity: ${SAS_TOKEN_VALIDITY:300} #In seconds
    - serviceName: cmc
      validity: ${SAS_TOKEN_VALIDITY:300} #In seconds
    - serviceName: publiclaw
      validity: ${SAS_TOKEN_VALIDITY:300} #In seconds

containers:
  mappings:
    - container: sscs
      jurisdiction: SSCS
      poBox: 12626
    - container: probate
      jurisdiction: PROBATE
      poBox: 12625
      ocrValidationUrl: ${OCR_VALIDATION_URL_PROBATE}
      paymentsEnabled: true
    - container: divorce
      jurisdiction: DIVORCE
      poBox: 12706
      ocrValidationUrl: ${OCR_VALIDATION_URL_DIVORCE}
      paymentsEnabled: true
    - container: finrem
      jurisdiction: DIVORCE
      poBox: 12746
      ocrValidationUrl: ${OCR_VALIDATION_URL_FINREM}
      paymentsEnabled: true
    - container: cmc
      jurisdiction: CMC
      poBox: 12747
    - container: bulkscan
      jurisdiction: BULKSCAN
      poBox: BULKSCANPO
      ocrValidationUrl: ${OCR_VALIDATION_URL_BULKSCAN_SAMPLE_APP}
      paymentsEnabled: true
    - container: publiclaw
      jurisdiction: PUBLICLAW
      poBox: 12879
      paymentsEnabled: false
      enabled: ${PUBLICLAW_ENABLED}

# clients region

idam:
  s2s-auth:
    url: ${S2S_URL:http://localhost:4552}
    secret: ${S2S_SECRET:AAAAAAAAAAAAAAAA}
    name: ${S2S_NAME:bulk_scan_processor}

document_management:
  url: http://dm-store:4460

error_notifications:
  url: ${ERROR_NOTIFICATIONS_URL:false}
  username: ${ERROR_NOTIFICATIONS_USERNAME:user}
  password: ${ERROR_NOTIFICATIONS_PASSWORD:password}

# end of clients region

scheduling:
  pool: ${SCHEDULING_POOL:10}
  lock_at_most_for: ${SCHEDULING_LOCK_AT_MOST_FOR:PT10M} # 10 minutes in ISO-8601
  task:
    scan:
      delay: ${SCAN_DELAY:30000} # In milliseconds
      enabled: ${SCAN_ENABLED:false}
    notifications_to_orchestrator:
      delay: ${NOTIFICATIONS_TO_ORCHESTRATOR_TASK_DELAY:30000} # in ms
      enabled: ${NOTIFICATIONS_TO_ORCHESTRATOR_TASK_ENABLED:false}
    reupload:
      batch: ${REUPLOAD_BATCH:20} # fetch 20 envelopes at once to process them. 0 for all
      delay: ${REUPLOAD_DELAY:1800000} # In milliseconds, 30min
      enabled: ${REUPLOAD_ENABLED:false}
      max_tries: ${REUPLOAD_MAX_TRIES:5}
    delete-rejected-files:
      enabled: ${DELETE_REJECTED_FILES_ENABLED:false}
      cron: ${DELETE_REJECTED_FILES_CRON}
      ttl: ${DELETE_REJECTED_FILES_TTL}
    delete-complete-files:
      enabled: ${DELETE_COMPLETE_FILES_ENABLED:false}
      cron: ${DELETE_COMPLETE_FILES_CRON}

envelope-access:
  mappings:
    - jurisdiction: SSCS
      readService: sscs
    - jurisdiction: BULKSCAN
      readService: bulk_scan_processor_tests

flyway:
  noop:
    strategy: "false"

process-payments:
  enabled: ${PROCESS_PAYMENTS_ENABLED:true}
