dependencies:
  - name: java
    version: ~2.5.0
    repository: '@hmctspublic'
  - name: servicebus
    version: ~0.0.3
    repository: '@hmctspublic'
    condition: bsp.servicebus.enabled
  - name: blobstorage
    version: ~0.0.4
    repository: '@hmctspublic'
    condition: bsp.blobstorage.enabled


