apiVersion: v1
kind: ConfigMap
metadata:
  name: ${SERVICE_NAME}-config
  namespace: ${NAMESPACE}
data:
  S2S_URL: "http://rpe-service-auth-provider-aat.service.core-compute-aat.internal"
  TEST_S2S_NAME: "bulk_scan_processor_tests"
  TEST_S2S_URL: "http://rpe-service-auth-provider-aat.service.core-compute-aat.internal"
  TEST_SCAN_DELAY: "4000"
  test_storage_container_name: "test"
  DOCUMENT_MANAGEMENT_URL: "http://dm-store-aat.service.core-compute-aat.internal"
