api_gateway_test_valid_certificate_thumbprint = "91CB9878CD88A6B442E19C12A557B0E79D054E65"
scan_enabled = "true"
reupload_enabled = "true"
orchestrator_notifications_task_delay = "3000"
orchestrator_notifications_task_enabled = "true"
blob_signature_verification_key_file = "test_public_key.der"
capacity = "2"
error_notifications_enabled = "true"
