ALTER TABLE envelopes
  ADD COLUMN classification VARCHAR(50) NOT NULL DEFAULT 'EXCEPTION',
  ADD COLUMN urgent BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE scannable_items
  ADD COLUMN documentType VARCHAR(100) NOT NULL DEFAULT 'Other';
